### ISSUE TITLE
[Bug]: The file is not saved completely 

### ISSUE THREAD

**Issue by ShinonomePratama** [pattlebass/Music-DJ#25] opened 2024-01-24 17:59 UTC
### What happened?

the music only plays for 5-11 even though I made it 47 seconds 

### Version

v1.5-beta

### OS/Browser version

Android 11 One UI 3.1

### Device information (phone model or PC specs)

SM-A105G

**Comment by pattlebass** [comment] 2024-11-02 15:44
Duplicate of #23

**Closed** 2024-11-02 15:45 UTC
Labels: bug
